name: flutter_bluetooth_serial
version: 0.4.0
description: A basic Flutter Bluetooth Serial library

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_launcher_icons: "^0.9.2"
  pull_to_refresh: ^2.0.0
  flutter:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/golfgo_logo.png"

flutter:
  plugin:
    platforms:
      android:
        package: io.github.edufolly.flutterbluetoothserial
        pluginClass: FlutterBluetoothSerialPlugin
